<?php

/**
 * @file
 * Contains node_like.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function node_like_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the node_like module.
    case 'help.page.node_like':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
